CATEGORIES_LIST = [
    "Política",
    "Geopolítica",
    "Internacional",
    "Economía y Finanzas",
    "Negocios y Empresas",
    "Justicia y Legal",
    "Transporte y Movilidad",
    "Industria",
    "Energía",
    "Tecnología y Digital",
    "Ciencia e Investigación",
    "Deporte",
    "Salud y Bienestar",
    "Inmobiliario y Construcción",
    "Agricultura y Alimentación",
    "Educación y Conocimiento",
    "Sociedad",
    "Cultura y Entretenimiento",
    "Consumo y Estilo de Vida",
    "Medio Ambiente y Clima",
    "Cultura Digital y Sociedad de la Información",
    "Filantropía e Impacto Social"
]
